# Generated by Django 4.2 on 2024-05-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafioadl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtarea',
            old_name='description',
            new_name='descripcion',
        ),
    ]
